### ISSUE TITLE
Query Tracker settings for Development

### ISSUE THREAD

**Issue by Krisha11** [ytsaurus/ytsaurus-ui#205]
Don't pass stage from "Settings/Development/YQL agent stage" in the chyt/spyt/ql query settings.

**Comment by Krisha11** [comment]
There is a PR with a solution to the problem, just need to merge it 
https://github.com/ytsaurus/ytsaurus-ui/pull/198

**Comment by zlobober** [comment]
What do you mean by "merge it"? Isn't it merged?

**Comment by Krisha11** [comment]
> What do you mean by "merge it"? Isn't it merged?

It wasn't
