### ISSUE TITLE
Allow user to issue and manage tokens from UI

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus-ui#241]
This issue is related to https://github.com/ytsaurus/ytsaurus/issues/227.

In OSS version in the bottom-left corner of the interface there is an avatar. After clicking on it, the context menu appears, which contains the option of changing the user password. We'd like to get another option of managing user tokens (which are used for various SDKs and CLI as an authentication scheme).

This should look like a separate page "/tokens", which provides the UI for the following commands of the API/CLI: issue_token, list_user_tokens, revoke_token. Note: these commands accept sha256-encoded password, not the raw password.

How it should look like:

1. Upon opening the page user must enter his password, this password is required as an `password_sha256` parameter for all API calls as an additional security measure.
2. If entered correctly, the list of the sha256-encoded tokens should appear (taken from `list_user_tokens` command).
3. Also, there should be a button "Issue new token", which results in creation of a new token, it should be added to the list. 
4. Near each token hash there should be a trash bin icon, which results in revoking this token (`revoke_token` command, token must be sent in token_sha256 form).

**Comment by vitshev** [comment]
Example of a potential ui
<img width="1544" alt="Screenshot 2024-02-08 at 17 53 58" src="https://github.com/ytsaurus/ytsaurus-ui/assets/3217636/d3b6c69d-647a-485f-a833-18b2c7cc6aca">
