### ISSUE TITLE
Add support for HTTPS proxy

### ISSUE THREAD

**Issue by sgburtsev** [ytsaurus/ytsaurus-ui#279]
At the moment it's impossible to use HTTPS protocol for http-proxy. I tried to specify in `clusters-config.json` `https://http-proxies-lb.yt.svc.local` (it returns `Error: getaddrinfo ENOTFOUND https`) and `http-proxies-lb.yt.svc.local:443` (`Error: socket hang up`).

**Comment by ma-efremoff** [comment]
Please look carefully at [the example](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/clusters-config.json.example) of the file, `proxy` field should not be prefixed with `http://` or `https://`, it is just a hostname. Please pay attention for [`secure`](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/clusters-config.json.example#L7) field, it is used to enable `https`.

**Comment by sgburtsev** [comment]
Thank you for your answer. `secure` field worked but I can't find a way to pass my own CA certificate or disable CA verification. Thus I get `Error: unable to get local issuer certificate`.

**Comment by sgburtsev** [comment]
Specifying CA by means of `NODE_EXTRA_CA_CERTS` environment variable worked for me.
