### ISSUE TITLE
Enhance YQL queries page with syntax suggestions

### ISSUE THREAD

**Issue by kaikash** [ytsaurus/ytsaurus-ui#300]
Hello!

It would be convenient to have syntax suggestions in the YQL queries page. This feature would work by offering possible completions as the user types their query. This addition would significantly simplify the process of writing queries, making it a more user-friendly experience. It can help in reducing errors and speeding up query development, especially for those who are still familiarizing themselves with YQL syntax.

**Comment by SimbiozizV** [comment]
This feature was added in the release [1.27.0](https://github.com/ytsaurus/ytsaurus-ui/releases/tag/ui-v1.27.0).
