### ISSUE TITLE
Show decimals as "numbers" in a table view

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#379]
Right now decimals are shown as bytes in table view:
<img width="622" alt="Screenshot 2024-02-26 at 13 45 06" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/9034cada-c9f5-4040-bed8-769e75400c16">

But in YQL view everything is fine:

<img width="469" alt="Screenshot 2024-02-26 at 13 49 33" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/f776d73d-e837-4103-b173-25c5f14e23f0">

**Comment by ma-efremoff** [comment]
Please provide steps to create such table.

**Comment by chegoryu** [comment]
```shell
$ yt create table //tmp/echunaev/test_table_d --attributes '{schema=[{name=ask_prices;type_v3={type_name=list;item={type_name=decimal;precision=35;scale=18}};required=true};]}'
$ yt write-table --format 'yson' --table //tmp/echunaev/test_table_d <<EOF
{"ask_prices"=["\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";];};
 {"ask_prices"=["\x80\0\0\0\0\0\0\x19:\xB8\3624\x82\xCC\0\0";"\x80\0\0\0\0\0\0\x19=\x7F}%=\xE0\0\0";"\x80\0\0\0\0\0\0\031E\xD3\x1D\xF7o\x1C\0\0";"\x80\0\0\0\0\0\0\x19H\x99\xA8\xE8*0\0\0";"\x80\0\0\0\0\0\0\x19K`3\xD8\345D\0\0";"\x80\0\0\0\0\0\0\x19N&\xBE\xC9\xA0X\0\0";"\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";"\x80\0\0\0\0\0\0\x19\xD6'V\xDDo,\0\0";];};
{"ask_prices"=["\x80\0\0\0\0\0\0\x19\x11\x16\xCE\x19\x8C\xA0\0\0";"\x80\0\0\0\0\0\0\x19:\xB8\3624\x82\xCC\0\0";"\x80\0\0\0\0\0\0\x19=\x7F}%=\xE0\0\0";"\x80\0\0\0\0\0\0\031E\xD3\x1D\xF7o\x1C\0\0";"\x80\0\0\0\0\0\0\x19H\x99\xA8\xE8*0\0\0";"\x80\0\0\0\0\0\0\x19K`3\xD8\345D\0\0";"\x80\0\0\0\0\0\0\x19N&\xBE\xC9\xA0X\0\0";"\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";"\x80\0\0\0\0\0\0\x19\xD6'V\xDDo,\0\0";];};
EOF
```

**Comment by ma-efremoff** [comment]
`yt write-table` doesn't look like a valid one:
```bash
$ YT_PROXY=`hostname`:8000 yt write-table --format 'yson' --table //tmp/test_table_d <<EOF
{"ask_prices"=["\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";];};
{"ask_prices"=["\x80\0\0\0\0\0\0\x19:\xB8\3624\x82\xCC\0\0";"\x80\0\0\0\0\0\0\x19=\x7F}%=\xE0\0\0";"\x80\0\0\0\0\0\0\031E\xD3\x1D\xF7o\x1C\0\0";"\x80\0\0\0\0\0\0\x19H\x99\xA8\xE8*0\0\0";"\x80\0\0\0\0\0\0\x19K`3\xD8\345D\0\0";"\x80\0\0\0\0\0\0\x19N&\xBE\xC9\xA0X\0\0";"\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";"\x80\0\0\0\0\0\0\x19\xD6'V\xDDo,\0\0";];};
{"ask_prices"=["\x80\0\0\0\0\0\0\x19\x11\x16\xCE\x19\x8C\xA0\0\0";"\x80\0\0\0\0\0\0\x19:\xB8\3624\x82\xCC\0\0";"\x80\0\0\0\0\0\0\x19=\x7F}%=\xE0\0\0";"\x80\0\0\0\0\0\0\031E\xD3\x1D\xF7o\x1C\0\0";"\x80\0\0\0\0\0\0\x19H\x99\xA8\xE8*0\0\0";"\x80\0\0\0\0\0\0\x19K`3\xD8\345D\0\0";"\x80\0\0\0\0\0\0\x19N&\xBE\xC9\xA0X\0\0";"\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";"\x80\0\0\0\0\0\0\x19\xD6'V\xDDo,\0\0";];};
EOF
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
YSON bindings required. Try to use other format or install bindings. Bindings are shipped as additional package and can be installed as Debian package "yandex-yt-python-yson" or as pip package "yandex-yt-yson-bindings"

***** Details:
YSON bindings required. Try to use other format or install bindings. Bindings are shipped as additional package and can be installed as Debian package "yandex-yt-python-yson" or as pip package "yandex-yt-yson-bindings" 
```
Is it works for you?

**Comment by chegoryu** [comment]
Looks like bash problem (it works with zsh).
Probably the simplest way is:
```shell
echo '{"ask_prices"=["\x80\0\0\0\0\0\0\x19l\xAE\xB7!\2524\0\0";];};' | yt write-table --format 'yson' --table //tmp/echunaev/test_table_d
```

<img width="850" alt="Screenshot 2024-02-28 at 15 03 44" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/61d264e3-95f4-40cc-b023-77232805e44f">
<img width="1925" alt="Screenshot 2024-02-28 at 15 03 49" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/89debc3b-abed-436a-b919-71d1dcd50650">

**Comment by chegoryu** [comment]
> I have uploaded the data through UI it looks fine

Are you sure? It looks fine only in YQL result preview, but in navigation it looks like binary string.

**Comment by ma-efremoff** [comment]
Please check `Table/YQL V3 types`, it should be checked:
<img width="687" alt="image" src="https://github.com/ytsaurus/ytsaurus-ui/assets/64027148/64a328b2-2958-40eb-9412-6b1f517f799f">

Yes I am sure, it looks fine in OSS version of UI:
<img width="1727" alt="image" src="https://github.com/ytsaurus/ytsaurus-ui/assets/64027148/746be54d-e53c-4367-a673-4ed65cde343c">

**Comment by chegoryu** [comment]
Oh, I use old version of UI (it doesn’t have such a checkbox).
<img width="608" alt="Screenshot 2024-02-28 at 18 55 58" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/2a01770e-41c0-4ae6-8942-63f2e725ec70">

Thank you, I will update it.

**Comment by ma-efremoff** [comment]
I've just found out that before [v1.10.0](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/CHANGELOG.md#1100-2023-12-22) you need to tune your `//sys/@ui_conig`:
```bash
yt set //sys/@ui_config/web_json_value_format 'yql'
```
