### ISSUE TITLE
If `//tmp/<login>` is a `map_node`, UI settings do not save

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#406]
As I see UI saves user settings in a `//tmp/<login>` document:

<img width="609" alt="Screenshot 2024-03-07 at 11 53 14" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/d8b679b8-ce1e-4795-9748-25d455417b37">

But when `//tmp/<login>` is a `map_node` UI still saves these settings but as this node childs:

<img width="563" alt="Screenshot 2024-03-07 at 11 55 43" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/094553ca-a4e5-48ec-b874-55c9b816c4cd">

However when `//tmp/<login>` is a `map_node` these settings do nothing (after change of any UI settings and page refresh you will get default settings back).

And this is a problem for two reasons:
1. `//tmp` is cleaned regularly
2. Usually people use `//tmp/<login>` `map_node` for their temporary data

So I believe that UI settings should be saved in a more suitable place.

**Comment by ma-efremoff** [comment]
`//tmp` just as an available default `map_node` directory it should not be used in production. You have to override configuration for your installation use [userSettingsConfig](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/src/%40types/core.d.ts#L59).

**Comment by chegoryu** [comment]
Thank you

Btw it is really hard to find all "bad" defaults for production cluster :(

**Comment by ma-efremoff** [comment]
The configuration is poorly documented at the moment and right now it is better to see available options in [the code](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/src/%40types/core.d.ts#L12-L131). Probably you also want to set [userColumnPresets](https://github.com/ytsaurus/ytsaurus-ui/blob/main/packages/ui/src/%40types/core.d.ts#L72) to allow to share links with selected columns of tables.
