### ISSUE TITLE
Make default ACO for new Queries configurable

### ISSUE THREAD

**Issue by Krock21** [ytsaurus/ytsaurus-ui#436]
Currently, "New Query" prepopulates ACO selector to `nobody`. We need to make it configurable somewhere

For now, we can add a new UI setting "default access control for new queries"

Later we may add similar thing to server side and allow cluster admins to configure default ACO that should be applied if user did not override it in UI settings

cc @achulkov2

**Comment by ma-efremoff** [comment]
For cluster specific options we use `//sys/@ui_config`.

**Comment by Krock21** [comment]
There are 2 parts in this issue:

1. Cluster-wide default for new queries for all users. It can be specified in `//sys/@ui_config`
2. User default for new queries that can be specified in Settings and that overrides default cluster-wide value. Similar to other settings like `Start page` `Default chyt alias` `Default path` `Query Tracker Stage` `YQL agent stage`

**Comment by ma-efremoff** [comment]
It looks like we cannot just add an option like `Default path` cause it is specific for current cluster, but queries might be started on any cluster, i.e. settings of current cluster aren't relevant to it. So we have to figure out what to do with it before start any work .

**Comment by ma-efremoff** [comment]
> For cluster specific options we use `//sys/@ui_config`. Also there is `get_supported_features` command.

And attempts to handle `//sys/@ui_config` on client side aren't going to be successfull. Probably, it should be handled on QT-backend side.
