### ISSUE TITLE
Can't open "new query" in new tab

### ISSUE THREAD

**Issue by ykuc** [ytsaurus/ytsaurus-ui#449]
<img width="467" alt="image" src="https://github.com/ytsaurus/ytsaurus-ui/assets/140019825/e5041bdc-bc45-450c-b45f-e45d13d38966">

When I click "new query" in open in the same tab.  Though, I push "control" and click "new" (

**Comment by vrozaev** [comment]
Hello @ykuc! It's should be fixed here https://github.com/ytsaurus/ytsaurus-ui/pull/481.
