### ISSUE TITLE
User settings are not applied if you go to the cluster from the page with clusters

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#471]
If you click on cluster on this page

<img width="1291" alt="Screenshot 2024-04-10 at 19 11 49" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/faba5e73-1f78-4974-b1db-4dec437a6d9f">

You will get default UI settings

<img width="371" alt="Screenshot 2024-04-10 at 19 12 13" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/29f3e214-be4e-4ec5-9496-9f146d205a68">

And only after F5 you will get your custom settings (from `//tmp/<your_user>` document):

<img width="354" alt="Screenshot 2024-04-10 at 19 13 13" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/e4ef7638-e348-4b25-b0e7-1b9b8f11bfc3">

**Comment by ma-efremoff** [comment]
@vitshev, please look at the issue, I am sure it was brought with #349

**Comment by kaikash** [comment]
1.30.0 didn't fix an issue
