### ISSUE TITLE
Add all possible permissions to "request permissions" form

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#474]
Right now it has only these permissions:

<img width="686" alt="Screenshot 2024-04-11 at 13 04 17" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/8087e056-75d6-4318-bd18-177fffe6b9ff">

But `modify_children` and `administer` are also often used. For example for this pattern of acl:

```
    "acl" = [
        {
            "action" = "allow";
            "subjects" = [
                "some-team-manager";
            ];
            "permissions" = [
                "administer";
                "write";
            ];
            "inheritance_mode" = "object_and_descendants";
        };
        {
            "action" = "allow";
            "subjects" = [
                "some-team";
            ];
            "permissions" = [
                "read";
                "write";
                "remove";
            ];
            "inheritance_mode" = "descendants_only";
        };
        {
            "action" = "allow";
            "subjects" = [
                "some-team";
            ];
            "permissions" = [
                "read";
                "modify_children";
            ];
            "inheritance_mode" = "object_only";
        };
    ];

```

**Comment by Krock21** [comment]
You can see all basic permissions here: https://github.com/ytsaurus/ytsaurus/blob/main/yt/yt/core/ytree/permission.h#L11-L48

I see `Register queue consumer vital` in the UI already. Looks like it is a flavor of `Register queue consumer` and I am not sure how it got to UI and how UI checks it

**Comment by rBunin** [comment]
Right now just add all. Need to design permissions  for each type of objects.

**Add all permissions types**
• Read
• Write
• Remove
• Administer
• modify_children
• Manage
• Mount
• Use
• Create
• Register queue consumer
• Register queue consumer vital

**Comment by chegoryu** [comment]
Thank you!
