### ISSUE TITLE
UI settings do not load if cluster is opened from cluster list page

### ISSUE THREAD

**Issue by kaikash** [ytsaurus/ytsaurus-ui#486]
First of all, settings are not applied on the main page (with the list of clusters). And if the cluster is opened from that page, settings won't be applied even in cluster page. If the page is reloaded, then settings are applied.

**Comment by kaikash** [comment]
Seems to be copy of https://github.com/ytsaurus/ytsaurus-ui/issues/471

**Comment by ma-efremoff** [comment]
Duplicate for #471
