### ISSUE TITLE
Href for operation description keys

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus-ui#496]
I have external system to execute graphs of tasks (like Nirvana in Yandex).
I add links to external system to the operation description likes this:
<img width="827" alt="Screenshot 2024-04-18 at 20 58 02" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/10f00213-25d2-4381-84ba-181d96819502">

But right now it is only possible to specify that description key is a link (via special attribute):
https://github.com/ytsaurus/ytsaurus-ui/blob/ca86bb84ceae35aa4b3cda11b38345ec7e26dc9c/packages/ui/src/ui/pages/operations/OperationDetail/tabs/details/Description.js#L27

Like this for example:

https://github.com/ytsaurus/ytsaurus/blob/a8a049235559916b09cba7d5e65610db16d1289a/yt/python/yt/wrapper/common.py#L407

However these links sometimes are very long, so I want to specify only task id, but add href attribute to it with full link, for example:
```shell
<
    "_type_tag"="url";
    "_href"="my.super.executor.com/ui/tasks/9a6e3f4c-7336-4971-ae18-7e4124cf9a02";
>"9a6e3f4c-7336-4971-ae18-7e4124cf9a02"
```

<img width="837" alt="Screenshot 2024-04-18 at 21 07 23" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/bb8fd36a-7657-46b2-8efc-4e01bc97dced">

**Comment by vrozaev** [comment]
Hello @chegoryu!

It's looks like you can specify both things - href and text for the link.

ytsaurus-ui covert yson to unipica [at this line](https://github.com/ytsaurus/ytsaurus-ui/blob/5250818deead43893caaf8f036493fa88e914442/packages/ui/src/ui/components/Yson/Yson.tsx#L95)

And according to [this unit test in unipica library ](https://github.com/gravity-ui/unipika/blob/863e02cbb24266ef35ccaeeab3cd10166ce5693d/test/converters/yson-to-unipika.test.ts#L140) you can specify both things like this:

```
{
  $value: {
    href: "https://example.com",
    text: "Example",
    title: "Example title",
  },
  $attributes: { _type_tag: "url" },
}
```

Please, let us know if it worked for you.

**Comment by chegoryu** [comment]
Wow, it works

<img width="306" alt="Screenshot 2024-04-23 at 16 28 43" src="https://github.com/ytsaurus/ytsaurus-ui/assets/29466571/fd6404de-41d3-4448-b165-d61f93046b80">

Thank you so much
