### ISSUE TITLE
Not working first primary master makes UI unavailble

### ISSUE THREAD

**Issue by kaikash** [ytsaurus/ytsaurus-ui#529]
Hello!

In case when first primary master doesn't work it makes UI not available, `api/cluster-params/<cluster>` fails with error

```
Oops! something went wrong. If the problem persists please report it via Bug Reporter.
{"message":"timeout of 5000ms exceeded","code":0,"yt_javascript_wrapper":{}}
```

It always takes the first master and makes `get` request to its `orchid` and this request fails with `Connection timed out` error. Seems to be because of this:
https://github.com/ytsaurus/ytsaurus-ui/blob/c849ecb6798badb92580a4c99fd0dbe3bbcd5359/packages/ui/src/ui/store/actions/system/masters.ts#L113

**Comment by ma-efremoff** [comment]
Are you using address of your primary master as `proxy`-field in your cluster-config.json?

**Comment by kaikash** [comment]
No, we are using http proxies for all communication between UI and YT. In turn, http proxy makes requests to first master orchid, which can be unavalable.

**Comment by vrozaev** [comment]
@kaikash should be fixed now, please check.
