### ISSUE TITLE
Utf-8 in QT

### ISSUE THREAD

**Issue by spiner2000** [ytsaurus/ytsaurus-ui#533]
If you got field name in utf-8 you will have "\<unsupported data type\>" in query output values
![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1374700/a00a9081-a17c-4f5a-afcc-2b101648c16b)
But if alias is set 
![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1374700/b7af3d9b-1d9e-4d0e-803a-5043711d8b74)
it works fine
![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1374700/38bae7e1-93b0-41d0-a7d1-0578b4fec08f)

**Comment by SimbiozizV** [comment]
The problem will be resolved as soon as https://github.com/ytsaurus/ytsaurus-ui/pull/597 will be added to the prod

**Comment by SimbiozizV** [comment]
fix in main
