### ISSUE TITLE
UTF-8 Unable to sort table with non-ASCII characters in field names from the UI menu.

### ISSUE THREAD

**Issue by spiner2000** [ytsaurus/ytsaurus-ui#600]
UI 1.34.0

Unable to sort table containing non-ASCII characters in field names from the UI menu. First of all, field names are displayed with wrong encoding in the "Sort table" popup. And then, if you choose at least one of these fields, the sort operation will fail with a field not found error.

**Comment by SimbiozizV** [comment]
this is the same problem as in https://github.com/ytsaurus/ytsaurus-ui/issues/533
The problem will be resolved as soon as https://github.com/ytsaurus/ytsaurus-ui/pull/597 will be added to the prod

**Comment by SimbiozizV** [comment]
fix in main
