### ISSUE TITLE
Management of users through UI

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus-ui#633]
This one is similar to #634, but for users.

There is a page with users (/users). It allows some of the actions with users, but lacks various useful administration primitives.
1) Deleting a user - I'd suggest adding it as a trash bin icon in the row corresponding to a user to the right. A modal window "Are you sure you want to delete..." should appear.

![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1856442/4f8fa1d1-d6c6-47cb-81b3-f9b727340549)

2) Renaming a user: I'd suggest adding a text box "Name" here, and if the name is changed, a Cypress request `set("//sys/users/<username>/@name", "<new name>")` should be issued

![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1856442/edcc89eb-52ca-476d-b890-6267ec9c6d0a)

3) Creating a new user

I'd suggest adding a new button "create new" which opens a modal window with the only text field "name"; to create a user, a Cypress request `create("user", attributes={"name": "<name>"})` should be issued. *NB*: this is a special form of a Cypress `create` request that lacks target path, and it is perfectly fine.

![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1856442/6358eacd-eeb8-458d-883f-9add622f98b7)

4) Set user password

Let's add a new vertical tab here called "Change password"

![image](https://github.com/ytsaurus/ytsaurus-ui/assets/1856442/99e42e28-8cb7-4d33-ae93-9921af8ed218)

First, you should check a check-permission request in order to see if logged user has a permission to change the selected user's password. This may be done via request `check_permission("<logged user>", "administer", "//sys/users/<selected user>")`. 

a) If the result is deny, let's just write a following red text:

```
No permission to change user <selected user> password. In order to change the password for a user, the "administer" permission on the user is required, or you must be a superuser.
```

b) If the result is allow, let's have a text box with masked characters:

```
New password: <********>
```

On save the request `set_user_password("<selected user>", "<new_password_sha256>")` should be issued.

**Comment by ma-efremoff** [comment]
Is it a good check below for `delete`, `rename` and `create` actions?
`check_permission("<logged user>", "administer", "//sys/users")`

**Comment by zlobober** [comment]
Unfortunately there is no direct relation between "administer" and ("delete"+"create") in this case (btw, there is no permission like "rename"). Server-side checks exactly the "administer" action, and nothing else.

**Comment by vrozaev** [comment]
Done in https://github.com/ytsaurus/ytsaurus-ui/pull/830
