### ISSUE TITLE
Show decimal cpus

### ISSUE THREAD

**Issue by polRk** [ytsaurus/ytsaurus-ui#675]
![telegram-cloud-photo-size-2-5251235103416376978-x](https://github.com/user-attachments/assets/3a10a72d-bd67-4d27-8671-9b392c196f6a)
![telegram-cloud-photo-size-2-5251235103416376982-x](https://github.com/user-attachments/assets/031d6e1f-d4d3-4152-bc07-d0d43de1f932)

**Comment by vrozaev** [comment]
Hi @kontakter! Which measure unit name should we use for cpu and network?
