### ISSUE TITLE
Use window.location instead of http proxy lb

### ISSUE THREAD

**Issue by polRk** [ytsaurus/ytsaurus-ui#676]
![telegram-cloud-photo-size-2-5251235103416377060-x](https://github.com/user-attachments/assets/16039f3c-5e4d-4165-b124-a9a48b7f3ecc)

![telegram-cloud-photo-size-2-5251235103416377065-x](https://github.com/user-attachments/assets/c15022f8-68f2-4d7d-b4b7-e5df485759f7)

**Comment by ma-efremoff** [comment]
You can provide `extenalProxy` field for each your cluster in `cluster-config.json`
