### ISSUE TITLE
List is not correctly previewed in UI

### ISSUE THREAD

**Issue by kaikash** [ytsaurus/ytsaurus-ui#683]
Hello!

I'm encountering an issue with a YQL query. When executing the following query:

```sql
SELECT Yson::ConvertToInt64List(Json::Parse(@@[42]@@))
```
the UI displays the result as:
```
column0: undefined
```

However, when I retrieve the query result via the CLI, the result is returned correctly:
```bash
yt read-query-result d26c3389-278f4086-1f101-7eb19587 --format json
{"column0":[42]}
```

This indicates that the issue is likely with the UI rendering of the result.

**Comment by kaikash** [comment]
The same with json.

**Comment by vrozaev** [comment]
Fixed by https://github.com/ytsaurus/ytsaurus-ui/commit/2009d96f9b822dbbd3e043628faa681731c4cd77
