### ISSUE TITLE
UI does not show statistics for running operations

### ISSUE THREAD

**Issue by vrozaev** [ytsaurus/ytsaurus-ui#710]
Probably because get_operation has two fields:

```
"job_statistics": {},
"job_statistics_v2": { ... }
```

And UI looks at job_statistics, which for some reason is empty for running operations

**Comment by ma-efremoff** [comment]
> And UI looks at job_statistics, which for some reason is empty for running operations

It looks like UI never tries to read [`job_statistics`](https://github.com/search?q=repo%3Aytsaurus%2Fytsaurus-ui%20job_statistics&type=code), but reads job_statistics_v2.

**Comment by vrozaev** [comment]
Incorrect ticket.
