### ISSUE TITLE
Perfomance problems in path-viewer

### ISSUE THREAD

**Issue by vrozaev** [ytsaurus/ytsaurus-ui#814]
### Problem
Right now path-viewer has perfomance problems, which a especially clear on default case.

By default, path-viewer trying to make `get /` command, which leads to massive response. Interface trying to render **whole** response in the same time and it's leads to interface lags and might even doesn't allow to use path-viewer.

### Solution
There is no clear solution at the moment, but next things could be done on ui side:

1. Process loaded data: BFS from the root and stop when you have enough data (make some limit). Mark everything else as truncated.
2. Introduce virtualised renderer for the data (render only chunk of data which a fit at the browser screen).
3. Introduce pagination for response.
4. Replace default `get /` command to `list ` - at least this change prevent perfomance problems right after path-viewer  open.

**Comment by ma-efremoff** [comment]
1,3 require corresponding API-features. As I know at the moment API does not provide them.

2. looks like a good idea, but we have to keep in mind even any virtualized component may struggle with large data.
4. Use `list` by default looks like a cheap and safe change.
