### ISSUE TITLE
Settings to disable redirect to proxies

### ISSUE THREAD

**Issue by futujaos** [ytsaurus/ytsaurus-ui#897]
Some actions like table download from UI generates URL to http proxy LB FQDN, but some installations may not have a public IP for proxies so such URLs will be unavailable. Let's made a property in YTsaurus k8s spec in `ui` section which will replace all such URLs with UI itself to handle requests through UI itself.

<img width="1104" alt="Screenshot 2024-12-02 at 14 03 49" src="https://github.com/user-attachments/assets/d0401e1b-36ff-4857-afe7-54e56e5e5c74">

**Comment by vrozaev** [comment]
> Let's made a property in YTsaurus k8s spec in ui section which will replace all such URLs with UI itself to handle requests through UI itself.

No, we should not do that, we need to make http proxy available to the user. If we will pass traffic via UI it might be overloaded.

**Comment by ma-efremoff** [comment]
> No, we should not do that, we need to make http proxy available to the user. If we will pass traffic via UI it might be overloaded.

Please pay attention for the comment. UI is not able to handle same load as backend.
Anyway there is an option that allows to enable behaviour you want, please see [directDownload]( https://github.com/ytsaurus/ytsaurus-k8s-operator/blob/3c4499bd92256006cb4f1a9185181c2ce682037c/pkg/ytconfig/ui.go#L41).

**Comment by futujaos** [comment]
thanks, `directDownload` will work for us by now
